name: Bickerstaff Realty
favicon: null
layout_spectrum: 0.25043
typography_spectrum: 0.74912
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3c3e3d'
    - '#bebfb1'
    - '#040404'
    - '#627178'
    - '#f3f8f2'
  brandStrength: 0.5435810121707618
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 0.8855562950484455
purpose: []
