name: Bickerstaff Realty
favicon: null
layout_spectrum: 0.10944260121323168
typography_spectrum: 0.839745840523392
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5435810121707618
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 0.8855562950484455
purpose: []
